### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by hadi-gharibi** [edmondja/test#1]
hey
sorry for put message here,but i need your help about your custom FM layer for keras,but u closed it.
how can i use that layer?can you make some example for using it?tnx

**Comment by edmondja** [comment]
Hello, 

I used it while puting it in layers.py then i imported it like a classical layer using the sequential api.
But you should use a word embedding layer if you just want to make a recommender system, as it has the same philosophy than the factorization machines layer and its already optimized for sparse matrices.

Kind regards,

Edmond

**Comment by hadi-gharibi** [comment]
thanks for answering
i see that,i used  functional api ,and i concatenate 2  layers,after that try to use your custom layer on top of it but it says :

> `Input 0 is incompatible with layer factorization_machines_layer_1: expected ndim=2+, found ndim=2`

i think i miss understand the input_dim and output_dim
is the output_dim should be the sum of #user and #items ?
what about input_dim?
sorry for silly questions :)
i'm a beginner

**Comment by hadi-gharibi** [comment]
i changed the '2+' to 2 and pass that (i dont know is that a right move or not)

here is my code:
```

user_in = Input(shape=(1,), dtype='int64', name='user_in')
u = Embedding(n_users,1, input_length=1, embeddings_regularizer=l2(1e-4))(user_in)
u = Flatten()(u)
movie_in = Input(shape=(1,), dtype='int64', name='movie_in')
m = Embedding(n_movies, 1, input_length=1, embeddings_regularizer=l2(1e-4))(movie_in)
m = Flatten()(m)
 
x = keras.layers.concatenate([u,m],axis=0)
 
x = FactorizationMachinesLayer(1)(x)

model = Model([user_in, movie_in], x)
model.compile(Adam(0.001), loss='mse')
```


summary :
> ____________________________________________________________________________________________________
> Layer (type)                     Output Shape          Param #     Connected to                     
> ====================================================================================================
> user_in (InputLayer)                        (None, 1)             0                                            
> ____________________________________________________________________________________________________
> movie_in (InputLayer)                     (None, 1)             0                                            
> ____________________________________________________________________________________________________
> embedding_19 (Embedding)         (None, 1, 1)          671         user_in[0][0]                    
> ____________________________________________________________________________________________________
> embedding_20 (Embedding)         (None, 1, 1)          9066        movie_in[0][0]                   
> ____________________________________________________________________________________________________
> flatten_19 (Flatten)                         (None, 1)             0           embedding_19[0][0]               
> ____________________________________________________________________________________________________
> flatten_20 (Flatten)                         (None, 1)             0           embedding_20[0][0]               
> ____________________________________________________________________________________________________
> concatenate_10 (Concatenate)     (None, 1)             0           flatten_19[0][0]                 
>                                                                                                flatten_20[0][0]                 
> ____________________________________________________________________________________________________
> factorization_machines_layer_13  (None, 1)             4           concatenate_10[0][0]             
> ====================================================================================================
> Total params: 9,741
> Trainable params: 9,741
> Non-trainable params: 0 
> 

from this for sure i can say the output_dim is wrong!but what should be?

and after try to fit this ,it shows this error

> ValueError: Input dimension mis-match. (input[1].shape[0] = 32, input[2].shape[0] = 64)
> Apply node that caused the error: Elemwise{Composite{(i0 + (-i1) + i2)}}[(0, 2)](InplaceDimShuffle{x,0}.0, factorization_machines_layer_10/factorization_machines_layer_12_target, Gemm{inplace}.0)
> Toposort index: 87
> Inputs types: [TensorType(float32, row), TensorType(float32, matrix), TensorType(float32, matrix)]
> Inputs shapes: [(1, 2), (32, 1), (64, 2)]
> Inputs strides: [(8, 4), (4, 4), (8, 4)]
> Inputs values: [array([[ 0.,  0.]], dtype=float32), 'not shown', 'not shown']
> Outputs clients: [[Elemwise{sqr,no_inplace}(Elemwise{Composite{(i0 + (-i1) + i2)}}[(0, 2)].0), Elemwise{Composite{((i0 * i1 * i2 * i3) / i4)}}[(0, 3)](TensorConstant{(1, 1) of 2.0}, InplaceDimShuffle{x,x}.0, InplaceDimShuffle{0,x}.0, Elemwise{Composite{(i0 + (-i1) + i2)}}[(0, 2)].0, Elemwise{Mul}[(0, 2)].0)]]
> 
> HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
> HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.


again sorry for ask to many q,but i really need this

**Comment by edmondja** [comment]
Im sorry i dont have time to check my code but it was working in older versions of Keras, i just used the factorization machines' formula and modified dense layer's matrices manipulations.

If you want to use it you should use the sequential API as it has been only tested with it, and as you are a beginner lol :p.

If you just want to build a recommender system in Keras, look at this video : https://www.youtube.com/watch?v=V2h3IOBDvrA&t=6210s .

Sorry for not having the time.

Regards,

Edmond
